#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ "$branch" = "main" -o "$branch" = "dev" ]; then
  echo "Direct push to main and dev branches is not allowed."
  exit 1
fi
